# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b46d58f9e73f508bea468b4821ad0d3136605439d102b702f0ce1963d707e2698793cacfdbcf6b931f04ed3b803744c4f33e81f3f5b263eaca3be232b62328

test:
  secret_key_base: 75dbbd3ab21c170e7205c5aede4e123191794fdb99a2cb6a63465aa7ca88c3551ae146be6c23ac9616d89ca23c91ba192939348c72cf596a7adddbf1c88810be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
